package com.jarvis.kmm.common.enum

import com.jarvis.kmm.MR
import dev.icerock.moko.resources.desc.StringDesc
import getStrings

enum class WeatherEnum(val code: Int, val nameWeather: StringDesc) {
    Sunny(113, getStrings(MR.strings.sunny)),
    PartlyCloudy(
        116,
        getStrings(MR.strings.partly_cloudy)
    ),
    Cloudy(
        119,
        getStrings(
            MR.strings.cloudy
        )
    ),
    VeryCloudy(
        122,
        getStrings(
            MR.strings.very_cloudy
        )
    ),
    Fog(143, getStrings(MR.strings.fog)),
    LightShowers(
        176,
        getStrings(
            MR.strings.lightShowers
        )
    ),
    LightSleetShowers(
        179,
        getStrings(
            MR.strings.lightShowers
        )
    ),
    LightSleet(
        182,
        getStrings(
            MR.strings.lightSleet
        )
    ),
    LightSleet2(
        185,
        getStrings(
            MR.strings.lightSleet
        )
    ),
    ThunderyShowers(
        200,
        getStrings(
            MR.strings.thunderyShowers
        )
    ),
    LightSnow(
        227,
        getStrings(
            MR.strings.lightSnow
        )
    ),
    HeavySnow(
        230,
        getStrings(
            MR.strings.heavy_snow
        )
    ),
    Fog2(248, getStrings(MR.strings.fog)),
    Fog3(260, getStrings(MR.strings.fog)),
    LightShowers2(
        263,
        getStrings(
            MR.strings.lightShowers,
        )
    ),
    LightRain(
        266,
        getStrings(
            MR.strings.lightRain,
        )
    ),
    LightSleet3(
        281,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    LightSleet4(
        284,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    LightRain2(
        293,
        getStrings(
            MR.strings.lightRain,
        )
    ),
    LightRain3(
        296,
        getStrings(
            MR.strings.lightRain,
        )
    ),
    HeavyShowers2(
        299,
        getStrings(
            MR.strings.heavy_showers,
        )
    ),
    HeavyRain2(
        302,
        getStrings(
            MR.strings.heavy_rain,
        )
    ),
    HeavyShowers3(
        305,
        getStrings(
            MR.strings.heavy_showers,
        )
    ),
    HeavyRain3(
        308,
        getStrings(
            MR.strings.heavy_rain,
        )
    ),
    LightSleet5(
        311,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    LightSleet6(
        314,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    LightSleet7(
        317,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    LightSnow2(
        320,
        getStrings(
            MR.strings.lightSnow,
        )
    ),
    LightSnowShowers2(
        323,
        getStrings(
            MR.strings.light_snow_showers,
        )
    ),
    LightSnowShowers3(
        326,
        getStrings(
            MR.strings.light_snow_showers,
        )
    ),
    HeavySnow2(
        329,
        getStrings(
            MR.strings.heavy_snow,
        )
    ),
    HeavySnow3(
        332,
        getStrings(
            MR.strings.heavy_snow,
        )
    ),
    HeavySnowShowers2(
        335,
        getStrings(
            MR.strings.heavySnowShowers,
        )
    ),
    HeavySnow4(
        338,
        getStrings(
            MR.strings.heavy_snow,
        )
    ),
    LightSleet8(
        350,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    LightShowers3(
        353,
        getStrings(
            MR.strings.lightShowers,
        )
    ),
    HeavyShowers(
        356,
        getStrings(
            MR.strings.heavy_showers,
        )
    ),
    HeavyRain(
        359,
        getStrings(
            MR.strings.heavy_rain,
        )
    ),
    LightSleetShowers2(
        362,
        getStrings(
            MR.strings.lightRain,
        )
    ),
    LightSleetShowers3(
        365,
        getStrings(
            MR.strings.lightRain,
        )
    ),
    LightSnowShowers(
        368,
        getStrings(
            MR.strings.light_snow_showers,
        )
    ),
    HeavySnowShowers3(
        371,
        getStrings(
            MR.strings.heavySnowShowers,
        )
    ),
    LightSleetShowers4(
        374,
        getStrings(
            MR.strings.thundery_heavy_rain,
        )
    ),
    LightSleet9(
        377,
        getStrings(
            MR.strings.lightSleet,
        )
    ),
    ThunderyShowers2(
        386,
        getStrings(
            MR.strings.thunderyShowers,
        )
    ),
    ThunderyHeavyRain(
        389,
        getStrings(
            MR.strings.thundery_heavy_rain,
        )
    ),
    ThunderySnowShowers(
        392,
        getStrings(
            MR.strings.thundery_snow_showers,
        )
    ),
    HeavySnowShowers(
        395,
        getStrings(
            MR.strings.heavySnowShowers,
        )
    )
}
